name: polymorphic_bot
version: 2.2.0
authors:
- Kenneth Endfinger <kaendfinger@gmail.com>
- samrg472 <samrg472@gmail.com>
description: Automation Bot
homepage: https://github.com/PolymorphicBot/
environment:
  sdk: ">=1.9.0-dev"
dependencies:
  analyzer: ">=0.23.0 <0.25.0"
  args: ">=0.12.2 <0.13.0"
  cipher: ">=0.7.1 <0.8.0"
  irc: ">=2.0.9 <2.2.0"
  path: ">=1.2.1 <2.0.0"
  http: ">=0.11.1 <0.12.0"
  html5lib: ">=0.12.0 <0.13.0"
  plugins: ">=1.0.3 <2.0.0"
  jsonx: ">=2.0.0 <3.0.0"
  usage: ">=1.0.0 <2.0.0"
dev_dependencies:
  unittest: ">=0.12.0-alpha.0 <0.13.0"
  grinder: ">=0.6.6+3 <0.7.0"
executables:
  polymorphic:
