name: yambot
version: 1.0.0
description: Making all your YAML IRC bot dreams a magical experience
homepage: https://github.com/DirectMyFile/YamBot
authors:
- Kenneth Endfinger <kaendfinger@gmail.com>
- samrg472 <samrg472@gmail.com>
dependencies:
  irc: ">=1.2.7 <1.3.0"
  yaml: ">=0.10.0 <1.0.0"
  quiver: ">=0.18.2 <0.20.0"
