name: polymorphic_bot
version: 2.2.0
authors:
- Kenneth Endfinger <kaendfinger@gmail.com>
- samrg472 <samrg472@gmail.com>
description: Automation Bot
homepage: https://github.com/PolymorphicBot/
environment:
  sdk: ">=1.8.0"
dependencies:
  analyzer: ">=0.22.4 <0.23.0"
  args: ">=0.12.2 <0.13.0"
  irc: ">=2.0.4 <3.0.0"
  path: ">=1.2.1 <2.0.0"
  http: ">=0.11.1 <0.12.0"
  plugins: ">=1.0.3 <2.0.0"
dev_dependencies:
  unittest: ">=0.11.5 <0.12.0"
  grinder: ">=0.6.5 <0.7.0"
executables:
  polymorphic:
