name: polymorphic_bot
version: 2.0.0
authors:
- Kenneth Endfinger <kaendfinger@gmail.com>
- samrg472 <samrg472@gmail.com>
description: Making all your IRC bot dreams a magical experience
homepage: https://github.com/DirectMyFile/YamBot
environment:
  sdk: '>=1.6.0'
dependencies:
  ansicolor: '>=0.0.9 <0.1.0'
  irc: '>=1.4.5 <1.5.0'
  path: '>=1.2.1 <2.0.0'
  plugins:
    git: git://github.com/samrg472/plugins.dart.git
dev_dependencies:
  scheduled_test: '>=0.11.1 <0.12.0'
