name: yambot
version: 1.0.1
authors:
- Kenneth Endfinger <kaendfinger@gmail.com>
- samrg472 <samrg472@gmail.com>
description: Making all your YAML IRC bot dreams a magical experience
homepage: https://github.com/DirectMyFile/YamBot
environment:
  sdk: '>=1.5.0'
dependencies:
  irc: '>=1.3.8 <1.4.0'
  plugins: '>=0.2.1 <0.3.0'
  yaml: '>=0.10.0 <2.0.0'
