name: polymorphic_bot
version: 2.1.2
authors:
- Kenneth Endfinger <kaendfinger@gmail.com>
- samrg472 <samrg472@gmail.com>
description: Making all your bot dreams a magical experience
homepage: https://github.com/PolymorphicBot/
environment:
  sdk: '>=1.8.0'
dependencies:
  console: '>=2.0.0 <3.0.0'
  irc: '>=2.0.0 <3.0.0'
  path: '>=1.2.1 <2.0.0'
  http: '>=0.11.1+1 <0.12.0'
  plugins:
    git: git://github.com/kaendfinger/plugins.dart.git
dev_dependencies:
  scheduled_test: '>=0.11.1 <0.12.0'
executables:
  polymorphic:
