name: polymorphic_bot
version: 2.2.0
authors:
- Kenneth Endfinger <kaendfinger@gmail.com>
- samrg472 <samrg472@gmail.com>
description: Automation Bot
homepage: https://github.com/PolymorphicBot/
environment:
  sdk: '>=1.8.0'
dependencies:
  args: ">=0.12.2+1 <0.13.0"
  console: '>=2.0.0 <3.0.0'
  irc: '>=2.0.0 <3.0.0'
  path: '>=1.2.1 <2.0.0'
  http: '>=0.11.1+1 <0.12.0'
  plugins:
    git: git://github.com/kaendfinger/plugins.dart.git
dev_dependencies:
  unittest: ">=0.11.5 <0.12.0"
  grinder: ">=0.6.5 <0.7.0"
executables:
  polymorphic:
